<script>
	import Nav from '../components/Nav.svelte';
	import MobileNav from '../components/MobileNav.svelte';
	import Footer from '../components/Footer.svelte';
	import WhyUs from '../components/WhyUs.svelte';
	import Nn from '../components/Nn.svelte';
	import Header from '../components/Header.svelte';

	export let segment;
	let lpages = [
		"sewer-drain-repair-contractor-wayne-il",
		"sewer-drain-repair-contractor-powers-lake-wi",
		"sewer-drain-repair-contractor-darien-il",
		"sewer-drain-repair-contractor-river-grove-il",
		"sewer-drain-repair-contractor-lindenwood-il",
		"sewer-drain-repair-contractor-creston-il",
		"sewer-drain-repair-contractor-highwood-il",
		"sewer-drain-repair-contractor-wadsworth-il",
		"sewer-drain-repair-contractor-sturtevant-wi",
		"sewer-drain-repair-contractor-steward-il",
		"sewer-drain-repair-contractor-bartlett-il",
		"sewer-drain-repair-contractor-long-grove-il",
		"sewer-drain-repair-contractor-ingleside-il",
		"sewer-drain-repair-contractor-sycamore-il",
		"sewer-drain-repair-contractor-glencoe-il",
		"sewer-drain-repair-contractor-great-lakes-il",
		"sewer-drain-repair-contractor-fox-lake-il",
		"sewer-drain-repair-contractor-prospect-heights-il",
		"sewer-drain-repair-contractor-ravinia-il",
		"sewer-drain-repair-contractor-naperville-il",
		"sewer-drain-repair-contractor-volo-il",
		"sewer-drain-repair-contractor-west-chicago-il",
		"sewer-drain-repair-contractor-bloomingdale-il",
		"sewer-drain-repair-contractor-south-elgin-il",
		"sewer-drain-repair-contractor-bristol-wi",
		"sewer-drain-repair-contractor-fox-valley-il",
		"sewer-drain-repair-contractor-racine-wi",
		"sewer-drain-repair-contractor-berwyn-il",
		"sewer-drain-repair-contractor-skokie-il",
		"sewer-drain-repair-contractor-hickory-hills-il",
		"sewer-drain-repair-contractor-elk-grove-village-il",
		"sewer-drain-repair-contractor-stickney-il",
		"sewer-drain-repair-contractor-lincolnshire-il",
		"sewer-drain-repair-contractor-park-city-il",
		"sewer-drain-repair-contractor-park-ridge-il",
		"sewer-drain-repair-contractor-twin-lakes-wi",
		"sewer-drain-repair-contractor-silver-lake-wi",
		"sewer-drain-repair-contractor-zenda-wi",
		"sewer-drain-repair-contractor-niles-il",
		"sewer-drain-repair-contractor-north-barrington-il",
		"sewer-drain-repair-contractor-hanover-park-il",
		"sewer-drain-repair-contractor-brookfield-il",
		"sewer-drain-repair-contractor-winfield-il",
		"sewer-drain-repair-contractor-barrington-il",
		"sewer-drain-repair-contractor-winthrop-harbor-il",
		"sewer-drain-repair-contractor-capron-il",
		"sewer-drain-repair-contractor-carpentersville-il",
		"sewer-drain-repair-contractor-cicero-il",
		"sewer-drain-repair-contractor-deerfield-il",
		"sewer-drain-repair-contractor-island-lake-il",
		"sewer-drain-repair-contractor-burlington-wi",
		"sewer-drain-repair-contractor-pleasant-prairie-wi",
		"sewer-drain-repair-contractor-oak-lawn-il",
		"sewer-drain-repair-contractor-oak-brook-il",
		"sewer-drain-repair-contractor-south-barrington-il",
		"sewer-drain-repair-contractor-dundee-il",
		"sewer-drain-repair-contractor-camp-lake-wi",
		"sewer-drain-repair-contractor-belvidere-il",
		"sewer-drain-repair-contractor-lake-geneva-wi",
		"sewer-drain-repair-contractor-lincoln-park-il",
		"sewer-drain-repair-contractor-evanston-il",
		"sewer-drain-repair-contractor-oak-park-il",
		"sewer-drain-repair-contractor-malta-il",
		"sewer-drain-repair-contractor-deer-park-il",
		"sewer-drain-repair-contractor-rochester-wi",
		"sewer-drain-repair-contractor-forest-park-il",
		"sewer-drain-repair-contractor-elk-grove-ca",
		"sewer-drain-repair-contractor-bristol-il",
		"sewer-drain-repair-contractor-caledonia-il",
		"sewer-drain-repair-contractor-genoa-city-wi",
		"sewer-drain-repair-contractor-kildeer-il",
		"sewer-drain-repair-contractor-ringwood-il",
		"sewer-drain-repair-contractor-lake-villa-il",
		"sewer-drain-repair-contractor-lafox-il",
		"sewer-drain-repair-contractor-mount-prospect-il",
		"sewer-drain-repair-contractor-wonder-lake-il",
		"sewer-drain-repair-contractor-roscoe-il",
		"sewer-drain-repair-contractor-north-riverside-il",
		"sewer-drain-repair-contractor-geneva-il",
		"sewer-drain-repair-contractor-montgomery-il",
		"sewer-drain-repair-contractor-wheeling-il",
		"sewer-drain-repair-contractor-wheaton-il",
		"sewer-drain-repair-contractor-saint-charles-il",
		"sewer-drain-repair-contractor-aurora-il",
		"sewer-drain-repair-contractor-rolling-meadows-il",
		"sewer-drain-repair-contractor-broadview-il",
		"sewer-drain-repair-contractor-clinton-wi",
		"sewer-drain-repair-contractor-avalon-wi",
		"sewer-drain-repair-contractor-north-aurora-il",
		"sewer-drain-repair-contractor-northfield-il",
		"sewer-drain-repair-contractor-salem-wi",
		"sewer-drain-repair-contractor-kenilworth-il",
		"sewer-drain-repair-contractor-prairie-view-il",
		"sewer-drain-repair-contractor-bassett-wi",
		"sewer-drain-repair-contractor-batavia-il",
		"sewer-drain-repair-contractor-carol-stream-il",
		"sewer-drain-repair-contractor-plato-center-il",
		"sewer-drain-repair-contractor-round-lake-heights-il",
		"sewer-drain-repair-contractor-whitewater-wi",
		"sewer-drain-repair-contractor-oakbrook-terrace-il",
		"sewer-drain-repair-contractor-woodworth-wi",
		"sewer-drain-repair-contractor-river-forest-il",
		"sewer-drain-repair-contractor-lincolnwood-il",
		"sewer-drain-repair-contractor-vernon-hills-il",
		"sewer-drain-repair-contractor-kingston-il",
		"sewer-drain-repair-contractor-lake-zurich-il",
		"sewer-drain-repair-contractor-delavan-wi",
		"sewer-drain-repair-contractor-la-grange-park-il",
		"sewer-drain-repair-contractor-glendale-heights-il",
		"sewer-drain-repair-contractor-cherry-valley-il",
		"sewer-drain-repair-contractor-westchester-il",
		"sewer-drain-repair-contractor-fontana-wi",
		"sewer-drain-repair-contractor-des-plaines-il",
		"sewer-drain-repair-contractor-streamwood-il",
		"sewer-drain-repair-contractor-waukegan-il",
		"sewer-drain-repair-contractor-buffalo-grove-il",
		"sewer-drain-repair-contractor-lake-forest-il",
		"sewer-drain-repair-contractor-springfield-wi",
		"sewer-drain-repair-contractor-milton-wi",
		"sewer-drain-repair-contractor-burlington-il",
		"sewer-drain-repair-contractor-east-dundee-il",
		"sewer-drain-repair-contractor-highland-park-il",
		"sewer-drain-repair-contractor-lombard-il",
		"sewer-drain-repair-contractor-inverness-il",
		"sewer-drain-repair-contractor-lakemoor-il",
		"sewer-drain-repair-contractor-honey-creek-wi",
		"sewer-drain-repair-contractor-lake-in-the-hills-il",
		"sewer-drain-repair-contractor-lagrange-park-il",
		"sewer-drain-repair-contractor-maple-park-il",
		"sewer-drain-repair-contractor-east-troy-wi",
		"sewer-drain-repair-contractor-woodridge-il",
		"sewer-drain-repair-contractor-monroe-center-il",
		"sewer-drain-repair-contractor-fort-sheridan-il",
		"sewer-drain-repair-contractor-willowbrook-il",
		"sewer-drain-repair-contractor-western-springs-il",
		"sewer-drain-repair-contractor-union-grove-wi",
		"sewer-drain-repair-contractor-hometown-il",
		"sewer-drain-repair-contractor-beloit-wi",
		"sewer-drain-repair-contractor-gurnee-il",
		"sewer-drain-repair-contractor-rochelle-il",
		"sewer-drain-repair-contractor-norridge-il",
		"sewer-drain-repair-contractor-morton-grove-il",
		"sewer-drain-repair-contractor-stone-park-il",
		"sewer-drain-repair-contractor-alden-il",
		"sewer-drain-repair-contractor-russell-il",
		"sewer-drain-repair-contractor-chicago-il",
		"sewer-drain-repair-contractor-la-grange-highlands-il",
		"sewer-drain-repair-contractor-hines-il",
		"sewer-drain-repair-contractor-franklin-park-il",
		"sewer-drain-repair-contractor-richmond-il",
		"sewer-drain-repair-contractor-south-beloit-il",
		"sewer-drain-repair-contractor-rosemont-il",
		"sewer-drain-repair-contractor-summit-il",
		"sewer-drain-repair-contractor-hodgkins-il",
		"sewer-drain-repair-contractor-riverside-il",
		"sewer-drain-repair-contractor-golf-il",
		"sewer-drain-repair-contractor-palatine-il",
		"sewer-drain-repair-contractor-wasco-il",
		"sewer-drain-repair-contractor-hawthorn-woods-il",
		"sewer-drain-repair-contractor-summit-argo-il",
		"sewer-drain-repair-contractor-huntley-il",
		"sewer-drain-repair-contractor-clare-il",
		"sewer-drain-repair-contractor-westmont-il",
		"sewer-drain-repair-contractor-winnetka-il",
		"sewer-drain-repair-contractor-arlington-heights-il",
		"sewer-drain-repair-contractor-round-lake-beach-il",
		"sewer-drain-repair-contractor-itasca-il",
		"sewer-drain-repair-contractor-indian-head-park-il",
		"sewer-drain-repair-contractor-elburn-il",
		"sewer-drain-repair-contractor-hinckley-il",
		"sewer-drain-repair-contractor-bridgeview-il",
		"sewer-drain-repair-contractor-wood-dale-il",
		"sewer-drain-repair-contractor-wauconda-il",
		"sewer-drain-repair-contractor-elmhurst-il",
		"sewer-drain-repair-contractor-antioch-il",
		"sewer-drain-repair-contractor-somers-wi",
		"sewer-drain-repair-contractor-lake-barrington-il",
		"sewer-drain-repair-contractor-justice-il",
		"sewer-drain-repair-contractor-burr-ridge-il",
		"sewer-drain-repair-contractor-hebron-il",
		"sewer-drain-repair-contractor-cary-il",
		"sewer-drain-repair-contractor-addison-il",
		"sewer-drain-repair-contractor-lindenhurst-il",
		"sewer-drain-repair-contractor-mchenry-il",
		"sewer-drain-repair-contractor-libertyville-il",
		"sewer-drain-repair-contractor-glen-ellyn-il",
		"sewer-drain-repair-contractor-rogers-park-il",
		"sewer-drain-repair-contractor-burbank-il",
		"sewer-drain-repair-contractor-kirkland-il",
		"sewer-drain-repair-contractor-lake-bluff-il",
		"sewer-drain-repair-contractor-schaumburg-il",
		"sewer-drain-repair-contractor-clarendon-hills-il",
		"sewer-drain-repair-contractor-gilberts-il",
		"sewer-drain-repair-contractor-williams-bay-wi",
		"sewer-drain-repair-contractor-eola-il",
		"sewer-drain-repair-contractor-elmwood-park-il",
		"sewer-drain-repair-contractor-marengo-il",
		"sewer-drain-repair-contractor-wilmette-il",
		"sewer-drain-repair-contractor-esmond-il",
		"sewer-drain-repair-contractor-amf-ohare-il",
	];
	export let nnCity;
	export let nnState;
	if(lpages.indexOf(segment)  > -1){
		nnCity = segment.replace('sewer-drain-repair-contractor-','');
		nnCity = segment.replace('hydro-jetting-','');
		let nnCS = nnCity.split("-");
		if (nnCS.length > 2){
			nnCity = encodeURI(nnCS[0]+""+nnCS[1]);
		}else{
			nnCity = encodeURI(nnCS[0]);
		}
		nnState = nnCS[nnCS.length - 1];
	}
</script>

<style>
</style>
<Header />
<MobileNav {segment}/>
<Nav {segment}/>
{#if segment === undefined}
	<main>
		<slot></slot>
	</main>
{:else}
	<main class="{segment} subpage">
		<slot></slot>
	</main>

{/if}
{#if lpages.indexOf(segment)  > -1 }
	<Nn nnCity="{nnCity}" nnState="{nnState}"></Nn>
{:else}
	<Nn></Nn>
{/if}
<Footer/>